#!/bin/sh
QUITER="$(echo -e "lock-screen\nreboot\nshutdown" | dmenu -fn "-xos4-roboto-medium-r-*-*-14-*" -c -l 3)"
case $QUITER in
	lock-screen)
		i3lock-fancy -p
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
esac
